# https://github.com/fastlane/fastlane

fastlane_version "2.10.0"

default_platform :ios

platform :ios do

  lane :test do
    clear_derived_data
    reset_simulators
    scan(clean: true, skip_build: false)
  end

end
